CC=clang
OBJ_DIR=obj

CXXFLAGS = \
	-DENABLE_TRACE \
	-I zmqpp-root/include \
	-Wall \
	-Wextra \
	-Wno-parentheses \
	-Wshadow \
	-Wunreachable-code \
	-g \
	-std=c++14

LDFLAGS = \
	-L zmqpp-root/lib \
	-lpthread \
	-lstdc++ \
	-lzmq \
	-lzmqpp

ifdef RELEASE

CXXFLAGS += \
	-O2 \
	-flto

else

CXXFLAGS += \
	-O0 \
	-fsanitize=address

LDFLAGS += \
	-fsanitize=address

endif
