include Makefile.defs

TARGET = echo_worker

CXXSRCS = \
	MutualHeartbeatMonitor.cpp \
	Worker.cpp \
	WorkerTask.cpp \
	ZMQIdentity.cpp \
	ZMQWorkerContext.cpp \
	echo_worker.cpp

include Makefile.rules
