COBJS = $(CSRCS:.c=.o) 
CXXOBJS = $(CXXSRCS:.cpp=.o) 

TARGETS = $(TARGET).elf
all:: $(TARGETS)

%.elf: $(COBJS) $(CXXOBJS)
	$(CC) $^ $(LDFLAGS) -o $@

#.PRECIOUS: %.o

%.o: %.c
	$(CC) $(CPPFLAGS) $(CFLAGS) -o $@ -c $<

%.o: %.cpp
	$(CC) $(CPPFLAGS) $(CXXFLAGS) -o $@ -c $<
