.PRECIOUS: $(OBJ_DIR)/%.o

OBJS = $(CXXSRCS:.cpp=.o) 
DST_OBJS = $(addprefix $(OBJ_DIR)/, $(OBJS))
DST_TARGET = $(OBJ_DIR)/$(TARGET)

all:: $(DST_TARGET)

$(DST_TARGET): $(DST_OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

$(OBJ_DIR)/%.o: %.cpp
	mkdir -p "$(OBJ_DIR)/`dirname $<`"
	$(CC) $(CXXFLAGS) -o $@ -c $<

clean:
	rm $(DST_OBJS) $(DST_TARGET) -f

install: $(DST_TARGET)
	mkdir -p $(DST_DIR)/bin
	cp $< $(DST_DIR)/bin
