name: Linux release build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      USR: runner
      WORKDIR: ${{ github.workspace }}

    steps:

    - uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Get runner UID/GID
      run: |
        echo "UID=$(id -u)" >> $GITHUB_ENV
        echo "GID=$(id -g)" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        set -euo pipefail

        docker build \
          --platform linux/amd64 \
          --build-arg USR="$USR" \
          --build-arg UID="$UID" \
          --build-arg GID="$GID" \
          -f docker/Dockerfile \
          -t mdp:1.0 .

    - name: Run container and execute build.sh
      run: |
        set -euo pipefail

        docker run --rm \
          --platform linux/amd64 \
          --name mdp \
          -u "$UID:$GID" \
          --mount type=bind,src="$WORKDIR",dst="/home/$USR/mdp" \
          mdp:1.0 \
          bash -lc "cd ~/mdp && make"
